# only one gitops master is supported between AWS,GCP,Azure
apiVersion: azure.caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: gitops-master
  namespace: default
spec:
  parameters:
    id: gitops-master
    region: West US
    version: "1.27.3"
    nodes:
      count: 3
      instanceType: Standard_B2s
    serviceSelector: gitops-master
    gitops:
      url: https://github.com/upbound/caas-cluster-configuration
      kubeConfigSecretRef:
        name: mcp-caas-kubeconfig
        namespace: default
  writeConnectionSecretToRef:
    name: azure-gitops-master-kubeconfig
