apiVersion: mcp.caas.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: caas
  namespace: default
spec:
  parameters:
    organizationName: upbound
    configuration: configuration-caas
  writeConnectionSecretToRef:
    name: mcp-caas-kubeconfig
